name: AbilityClasses
version: ${project.version}
main: me.saltyy.abilityclasses.AbilityClasses
api-version: 1.16
authors: [Saltyy]
website: https://gitlab.com/Saltyy/minecraft-class-plugin
description: Adds Classes with special Abilitys to your world - each class got their unique effects
commands:
  abilityinfo:
      description: Gives you more info about an ability with /abilityinfo <ability>
      usage: /abilityinfo <ability>
  abilityreroll:
    description: Allows you to reroll someone's power with /abilityreroll <name>
    usage: /abilityreroll <name>
  ability:
    description: Allows you to set your power with /ability <hero>
    usage: /ability <hero> <name>
  abilityconfigreload:
    description: Allows you to reload the plugin configs
    usage: /abilityconfigreload
permissions:
  playerclasses.ability:
    description: Allows them to use /ability
    default: op
  playerclasses.abilityreroll:
    description: Allows them to use /abilityreroll
    default: op
  playerclasses.abilityinfo:
    description: Allows them to use /abilityinfo
    default: true